name: runtime_2
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
version: 1.0.0
homepage: https://github.com/DISCOOS/dart-runtime-2
author: DISCO Open Source <support@discoos.org>

environment:
  sdk: '>=2.2.0 <3.0.0'

# Change when IPR is resolved with Stable/Kernel
publish_to: none

dependencies:
  yaml: ">=2.2.1 <3.0.0"
  meta: ^1.1.5
  pubspec_parse: ^0.1.8
  isolate_executor_2: ^1.0.0

dependency_overrides:
  isolate_executor_2:
    git: https://github.com/DISCOOS/dart-isolate-executor-2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
